"""Add nullable variable for description

Revision ID: de822b02b291
Revises: fbdb728c76bc
Create Date: 2025-12-06 19:14:53.174280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de822b02b291"
down_revision: Union[str, Sequence[str], None] = "fbdb728c76bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "description", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
