"""Add title and description for product

Revision ID: e7537a8f6402
Revises: 31bc88db96c5
Create Date: 2026-01-14 19:53:54.710136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7537a8f6402"
down_revision: Union[str, Sequence[str], None] = "16d34d6e647c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("title", sa.String(length=150), nullable=False))
    op.add_column("products", sa.Column("description", sa.Text(), nullable=False))
    op.alter_column(
        "products",
        "id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('products_id_seq'::regclass)"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('products_id_seq'::regclass)"),
    )
    op.drop_column("products", "description")
    op.drop_column("products", "title")
    # ### end Alembic commands ###
