"""Add images table and relationship between user table

Revision ID: 3872d11c1be0
Revises: e7537a8f6402
Create Date: 2026-01-30 19:14:36.285066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3872d11c1be0"
down_revision: Union[str, Sequence[str], None] = "e7537a8f6402"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_key", sa.String(length=500), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("products", sa.Column("price", sa.Float(), nullable=False))
    op.add_column(
        "products", sa.Column("file_key", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "products", sa.Column("file_name", sa.String(length=255), nullable=True)
    )
    op.add_column("products", sa.Column("file_size", sa.BigInteger(), nullable=True))
    op.add_column(
        "products", sa.Column("file_content_type", sa.String(length=100), nullable=True)
    )
    op.add_column("products", sa.Column("is_published", sa.Boolean(), nullable=False))
    op.add_column("products", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("products", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "updated_at")
    op.drop_column("products", "created_at")
    op.drop_column("products", "is_published")
    op.drop_column("products", "file_content_type")
    op.drop_column("products", "file_size")
    op.drop_column("products", "file_name")
    op.drop_column("products", "file_key")
    op.drop_column("products", "price")
    op.drop_table("product_images")
    # ### end Alembic commands ###
