"""Add is_seller method for UserModel

Revision ID: aafe80be77ad
Revises: b39f6dc03b05
Create Date: 2026-01-01 23:24:21.094315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aafe80be77ad"
down_revision: Union[str, Sequence[str], None] = "b39f6dc03b05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_seller", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_seller")
    # ### end Alembic commands ###
